package pe.egcc.eurekaappcs.view;

import javax.swing.JInternalFrame;
import pe.egcc.eurekaappcs.domain.Empleado;
import pe.egcc.eurekaappcs.util.Memoria;

/**
 *
 * @author Gustavo Coronel
 */
public class FormularioMDI extends javax.swing.JFrame {

  /**
   * Creates new form FormularioMDI
   */
  public FormularioMDI() {
    initComponents();
    establecerTitulo();
    //setExtendedState(MAXIMIZED_BOTH);
  }

  private void establecerTitulo() {
    Empleado bean = (Empleado) Memoria.get("usuario");
    String titulo = "EUREKA [Usuario: " + bean.getUsuario() + "]";
    this.setTitle(titulo);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoSalir = new javax.swing.JMenuItem();
        menuProcesosClave = new javax.swing.JMenu();
        menuProcesosDeposito = new javax.swing.JMenuItem();
        menuProcesoRetiro = new javax.swing.JMenuItem();
        menuProcesoCambioclave = new javax.swing.JMenuItem();
        menuTablas = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenu();
        menuReportes = new javax.swing.JMenu();
        menuUtil = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setText("Archivo");

        menuArchivoSalir.setText("Salir");
        menuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoSalir);

        menuBar.add(menuArchivo);

        menuProcesosClave.setText("Procesos");

        menuProcesosDeposito.setText("Depósito");
        menuProcesosDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesosDepositoActionPerformed(evt);
            }
        });
        menuProcesosClave.add(menuProcesosDeposito);

        menuProcesoRetiro.setText("Retiro");
        menuProcesoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoRetiroActionPerformed(evt);
            }
        });
        menuProcesosClave.add(menuProcesoRetiro);

        menuProcesoCambioclave.setText("Cambio de Clave");
        menuProcesoCambioclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProcesoCambioclaveActionPerformed(evt);
            }
        });
        menuProcesosClave.add(menuProcesoCambioclave);
        menuProcesoCambioclave.getAccessibleContext().setAccessibleName("Cambio_Clave");

        menuBar.add(menuProcesosClave);

        menuTablas.setText("Tablas");
        menuBar.add(menuTablas);

        menuConsultas.setText("Consultas");
        menuBar.add(menuConsultas);

        menuReportes.setText("Reportes");
        menuBar.add(menuReportes);

        menuUtil.setText("Util");
        menuBar.add(menuUtil);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void menuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoSalirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuArchivoSalirActionPerformed

  private void menuProcesosDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesosDepositoActionPerformed
    cargarFormulario(DepositoView.class);
  }//GEN-LAST:event_menuProcesosDepositoActionPerformed

    private void menuProcesoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoRetiroActionPerformed
     cargarFormulario(RetiroView.class);
    }//GEN-LAST:event_menuProcesoRetiroActionPerformed

    private void menuProcesoCambioclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProcesoCambioclaveActionPerformed
    cargarFormulario(IngreseDatosView.class);
    }//GEN-LAST:event_menuProcesoCambioclaveActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormularioMDI().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuProcesoCambioclave;
    private javax.swing.JMenuItem menuProcesoRetiro;
    private javax.swing.JMenu menuProcesosClave;
    private javax.swing.JMenuItem menuProcesosDeposito;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuTablas;
    private javax.swing.JMenu menuUtil;
    // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      JInternalFrame view;
      view = buscarFormulario(aClass);
      if (view == null) {
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
        view.setVisible(true);
      }
      // Activando el formulario
      view.setSelected(true);
    } catch (Exception e) {
    }
  }

  private JInternalFrame buscarFormulario(Class<?> aClass) {
    JInternalFrame view = null;
    for (JInternalFrame bean : desktopPane.getAllFrames()) {
      if (aClass.isInstance(bean)) {
        view = bean;
        break;
      }
    }
    return view;
  }

}
